library('OpenImageR')
library('entropy')

im = readImage('mondriaan.png')
im_gray = rgb_2gray(im)

im_edge_sobel = edge_detection(im_gray, method = "Sobel", conv_mode = 'same')
im_edge_sobel_2 = round(im_edge_sobel, 2)
entropy_sobel = entropy(im_edge_sobel[,1:dim(im_edge_sobel)[2]])
cat("Entropy sobel = ")
cat(entropy_sobel)
cat('\n')

im_edge_scharr = edge_detection(im_gray, method = "Scharr", conv_mode = 'same')
im_edge_scharr_2 = round(im_edge_scharr, 2)
entropy_scharr = entropy(im_edge_scharr[,1:dim(im_edge_scharr)[2]])
cat("Entropy scharr = ")
cat(entropy_scharr)
cat('\n')

im_edge_roberts_cross = edge_detection(im_gray, method = "Roberts_cross", conv_mode = 'same')
im_edge_roberts_cross_2 = round(im_edge_roberts_cross, 2)
entropy_roberts_cross = entropy(im_edge_roberts_cross[,1:dim(im_edge_roberts_cross)[2]])
cat("Entropy RC = ")
cat(entropy_roberts_cross)
cat('\n')

im_edge_prewitt = edge_detection(im_gray, method = "Prewitt", conv_mode = 'same')
im_edge_prewitt_2 = round(im_edge_prewitt, 2)
entropy_prewitt = entropy(im_edge_prewitt[,1:dim(im_edge_prewitt)[2]])
cat("Entropy prewitt = ")
cat(entropy_prewitt)
cat('\n')

im_edge_log = edge_detection(im_gray, method = "LoG", conv_mode = 'same')
im_edge_log_2 = round(im_edge_log, 2)
entropy_log = entropy(im_edge_log[,1:dim(im_edge_log)[2]])
cat("Entropy LoG = ")
cat(entropy_log)
cat('\n')

im_edge_frei_chen = edge_detection(im_gray, method = "Frei_chen", conv_mode = 'same')
im_edge_frei_chen_2 = round(im_edge_frei_chen, 2)
entropy_frei_chen = entropy(im_edge_frei_chen[,1:dim(im_edge_frei_chen)[2]])
cat("Entropy FC = ")
cat(entropy_frei_chen)
cat('\n')

length(unique(c(im_edge_log_2)))